services:
  # 1. Nginx: 
  nginx:
    image: ${DOCKERHUB_USERNAME}/nginx-monitor:latest
    container_name: nginx-server
    ports:
      - "8080:80"
      - "5432:5432"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/reddit_frontend/dist:/usr/share/nginx/html
      - ./nginx_logs:/var/log/nginx # Mount nginx logs for Promtail to read
    networks:
      - global-monitor-net
    restart: unless-stopped

  # 2. Exporter: Phiên dịch
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx:80/stub_status
      - -web.telemetry-path=/metrics
      - -nginx.timeout=5s
    ports:
      - "9113:9113" # Expose port for Prometheus scraping
    networks:
      - global-monitor-net
    depends_on:
      - nginx
    labels:
      - "prometheus.monitor=true"
      - "prometheus.scrape_port=9113"
      - "prometheus.job=nginx" # Đặt tên job cho dễ quản lý
    restart: unless-stopped

networks:
  global-monitor-net:
    external: true

  