services:
  # 1. Nginx: 
  nginx:
    image: ${DOCKERHUB_USERNAME}/nginx-monitor:latest
    container_name: nginx-server
    ports:
      - "8080:80" # Truy cập web tại localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - global-monitor-net
    restart: unless-stopped

  # 2. Exporter: Phiên dịch
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx:80/stub_status
      - -web.telemetry-path=/metrics
      - -nginx.timeout=5s
    networks:
      - global-monitor-net
    depends_on:
      - nginx
    # --- THÊM PHẦN NÀY ---
    labels:
      - "prometheus.monitor=true"
      - "prometheus.scrape_port=9113"
      - "prometheus.job=nginx" # Đặt tên job cho dễ quản lý
    restart: unless-stopped

networks:
  global-monitor-net:
    external: true

  