services:
  # 1. Nginx: 
  nginx:
    image: ${DOCKERHUB_USERNAME}/nginx-monitor:latest
    container_name: nginx-server
    ports:
      - "8080:80" # Truy cập web tại localhost:8080
    networks:
      - monitor-net

  # 2. Exporter: Phiên dịch
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx:80/stub_status
    networks:
      - monitor-net
    depends_on:
      - nginx

  # 3. Prometheus: Lưu trữ dữ liệu
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090" # Xem dữ liệu thô tại localhost:9090
    networks:
      - monitor-net
    
# 4. Grafana: Giao diện hiển thị biểu đồ
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=trunghalo2005 # Mật khẩu đăng nhập

    volumes:
      - grafana_data:/var/lib/grafana
      # Nạp các file cấu hình tự động (Provisioning)
      - ./grafana/provisioning:/etc/grafana/provisioning
      # Nạp file JSON chứa biểu đồ của bạn
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - monitor-net
    depends_on:
      - prometheus
  
  # --- LOGGING SYSTEM ---
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Đọc log trực tiếp từ Docker Engine
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net
  
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: 

  