events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        # 1. Trang web chính của bạn
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # 2. Cửa sổ nhả dữ liệu giám sát (QUAN TRỌNG)
        # Exporter sẽ vào đây để lấy thông số CPU/RAM/Request của Nginx
        location /stub_status {
            stub_status on;
            access_log off;
            allow all; # Trong thực tế nên giới hạn IP, nhưng đồ án thì để all cho dễ
        }
    }
}