name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code từ GitHub về máy ảo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Kiểm tra cú pháp Nginx (Bảo vệ hệ thống khỏi lỗi cấu hình)
      - name: Validate Nginx configuration
        run: docker run --rm -v ${{ github.workspace }}/nginx.conf:/etc/nginx/nginx.conf:ro nginx:alpine nginx -t

      # 3. Đăng nhập vào Docker Hub (Dùng Secret bạn đã cài)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build Image từ Dockerfile và Push lên Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # CHỖ NÀY: Thay 'TEN_DOCKER_HUB_CUA_BAN' bằng Username Docker của bạn
          tags: trinhtrung175/nginx-monitor:latest 

      - name: Success Message
        run: echo "Chúc mừng! Image đã được đẩy lên Docker Hub thành công."